spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cdrm
    username: cdrm
    password: cdrm
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:2305/realms/cdrm
