#!/bin/bash
# Installs ArgoCD into minikube and points it at the GitOps demo repo (run
# setup-gitops-repo.sh first) — one Application per GitOps-managed namespace in
# seed/data.yaml, generated by generate-applications.py so there's a single source of
# truth between cdrm's own K8sGitopsConfig and what ArgoCD actually syncs.
#
# Idempotent — safe to re-run (e.g. after changing seed/data.yaml's k8s_namespaces).

set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
ARGOCD_NAMESPACE="argocd"

if ! command -v kubectl > /dev/null 2>&1; then
  echo "Error: 'kubectl' is required but not installed." >&2
  exit 1
fi

if ! kubectl config current-context > /dev/null 2>&1 || [ "$(kubectl config current-context)" != "minikube" ]; then
  echo "Error: kubectl's current context must be 'minikube'. Run 'minikube start' first." >&2
  exit 1
fi

echo "Creating namespace '${ARGOCD_NAMESPACE}' (if missing)..."
kubectl create namespace "${ARGOCD_NAMESPACE}" --dry-run=client -o yaml | kubectl apply -f -

echo "Installing ArgoCD (development/argocd/install.yaml, vendored from the upstream stable manifest)..."
# --server-side: one of the CRDs (applicationsets.argoproj.io) is too large for
# client-side apply's kubectl.kubernetes.io/last-applied-configuration annotation
# (>262144 bytes) — server-side apply doesn't store that annotation at all.
kubectl apply --server-side --force-conflicts -n "${ARGOCD_NAMESPACE}" -f "${DIR}/install.yaml"

echo "Waiting for argocd-server to be ready..."
kubectl -n "${ARGOCD_NAMESPACE}" rollout status deployment/argocd-server --timeout=300s

echo "Applying Applications generated from seed/data.yaml..."
GENERATED="$(mktemp)"
trap 'rm -f "${GENERATED}"' EXIT
python3 "${DIR}/generate-applications.py" > "${GENERATED}"
kubectl apply -f "${GENERATED}"

# Prune Applications from a previous run that generate-applications.py wouldn't produce
# anymore (e.g. seed/data.yaml changed, or its naming logic changed) — otherwise a
# rename or a removed namespace just leaves the old Application behind forever.
DESIRED_NAMES="$(python3 -c "
import sys, yaml
for doc in yaml.safe_load_all(open('${GENERATED}')):
    print(doc['metadata']['name'])
")"
EXISTING_NAMES="$(kubectl -n "${ARGOCD_NAMESPACE}" get applications -o jsonpath='{.items[*].metadata.name}')"
for name in ${EXISTING_NAMES}; do
  if ! grep -qx "${name}" <<< "${DESIRED_NAMES}"; then
    echo "  removing stale Application '${name}'"
    kubectl -n "${ARGOCD_NAMESPACE}" delete application "${name}"
  fi
done

echo "Done."
echo "UI: run development/argocd/portforward.sh, then open https://localhost:1961"
echo "Login: user 'admin', password: kubectl -n ${ARGOCD_NAMESPACE} get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d"
